// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI29AV.Context;

#nullable disable

namespace WebAPI29AV.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250525081409_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Rol", b =>
                {
                    b.Property<int>("PKRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PKRol"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PKRol");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            PKRol = 1,
                            Name = "Alumno"
                        },
                        new
                        {
                            PKRol = 2,
                            Name = "Maestro"
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("PKUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PKUser"));

                    b.Property<int?>("FKRol")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PKUser");

                    b.HasIndex("FKRol");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            PKUser = 1,
                            FKRol = 2,
                            Name = "Josafat",
                            Password = "1910",
                            Username = "Joss"
                        },
                        new
                        {
                            PKUser = 2,
                            FKRol = 1,
                            Name = "Roberto",
                            Password = "1910",
                            Username = "Kaiser"
                        },
                        new
                        {
                            PKUser = 3,
                            FKRol = 1,
                            Name = "Kaiser",
                            Password = "1910",
                            Username = "Ackerman"
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.HasOne("Domain.Entities.Rol", "Roles")
                        .WithMany()
                        .HasForeignKey("FKRol");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
